### ISSUE TITLE
Lighthouse aria-* rule violation

### ISSUE THREAD

**Issue by luisrudge** [calibreapp/react-live-chat-loader#106]
## Describe the bug
Lighthouse is complaining about an aria-* rule violation: `[aria-*] attributes do not match their roles `

## How To Reproduce
```
          <LiveChatLoaderProvider providerKey="lksanlsknksal" provider="drift">
             ...
            <Drift />
          </LiveChatLoaderProvider>
```

## Expected behaviour
No accessibility errors should be present

## Screenshots
<img width="923" alt="image" src="https://user-images.githubusercontent.com/941075/135566277-59e11be0-be26-4cf1-ac63-f08139cb38b7.png">

**Comment by benschwarz** [comment]
Hey @luisrudge, thanks for logging this.

Are you aware of how the aria attributes are mismatched or what a fix might be? 

If so, please feel free to file a PR correcting behaviour, or add notes here with any additional information you're able to provide.

**Comment by luisrudge** [comment]
I did some research and according to [this](https://github.com/GoogleChrome/lighthouse/issues/12630) I think you can't apply `aria-label` without having a `role` as well. 

<img width="712" alt="image" src="https://user-images.githubusercontent.com/941075/135645555-05ce5cb4-75e5-4162-978e-621e11b153c0.png">

**Comment by benschwarz** [comment]
Thanks for reporting AND fixing @luisrudge 🥇 Appreciated 👍 

We've just merged your change and added you as a contributor. Release 2.7.2 is out the door!
