### ISSUE TITLE
Inline style for Drift causing cutoff effects

### ISSUE THREAD

**Issue by Carlo-Defilippis** [calibreapp/react-live-chat-loader#115]
## Describe the bug
When using drift chat on my Gatsby site, the first pop up shows up correctly that greets the user but upon changing routes/url's it cuts off the pop up box due to the inline style setting of "width: 76px !important"

## How To Reproduce
the bug can currently bee seen here on my staging site https://dripsstaging.gtsb.io

1. Click on the X on the pop up box when greeted after it pops up from hovering over button or idle period.
2. change to any other page on the website
3. See error

## Expected behavior
Second pop up box should not have a set width of 76px

## Video
https://youtu.be/hlmPlh60EZE

**Comment by mikedijkstra** [comment]
@Carlo-Defilippis Thanks for filing this issue.

The fake drift widget is removed when the real one loads, as you [can see here](https://github.com/calibreapp/react-live-chat-loader/blob/main/src/components/Drift/index.tsx#L71).

Do you think the real drift widget takes some sizing from the fake widget before it loads?

**Comment by Carlo-Defilippis** [comment]
I have a feeling this has something to do with Gatsby. Now I am getting this error from the module 
<a href="https://ibb.co/LkCY65h"><img src="https://i.ibb.co/LkCY65h/apikey.png" alt="apikey" border="0"></a>
"No api key given to react-live-chat-loader"
The undefined in the console is the state of the module.

**Comment by Carlo-Defilippis** [comment]
After much trials and testing I have determined this issue is a styling issue on the drift chat bot itself while firing the "conversation:playbookFired" function. Thanks for your help regardless!

**Comment by mikedijkstra** [comment]
@Carlo-Defilippis Glad to hear you were able to get to the cause of the issue!
