### ISSUE TITLE
[Bug] Typing errors conflict with documentation

### ISSUE THREAD

**Issue by IngoVals** [calibreapp/react-live-chat-loader#122]
Using the Messenger component in Typescript results in annoying typing errors. The props field is defined with

`providerKey: Provider | undefined;` but would be better served as `providerKey?: Provider` so we are not forced to do `<Messenger providerKey={undefined} />` or `<Messenger providerKey='messenger' />`

This also does not match with the documentation which doesn't indicate any props are necessary. The same is true with the mention of `locale `property which does not exist.

Using version **2.7.3**

**Comment by benschwarz** [comment]
> Using the Messenger component in Typescript results in annoying typing errors.

I understand your frustration with implementation issues or gaps in documentation, but please remember that saying something is annoying isn't helpful and does not provide useful insight to the issue diagnosis.

> The props field is defined with
> 
> `providerKey: Provider | undefined;` but would be better served as `providerKey?: Provider` so we are not forced to do `<Messenger providerKey={undefined} />` or `<Messenger providerKey='messenger' />`

> This also does not match with the documentation which doesn't indicate any props are necessary. 

Do you think you'd be in a position to write a PR implementing your suggestions?

>  The same is true with the mention of locale property which does not exist.

I haven't reviewed the library in a while, but from a brief look the locale property is mapped in the messenger provider. Can you describe how `locale` does not exist in a little more detail?

**Comment by IngoVals** [comment]
Absolutely should be more technical, but **annoying** wasn't to represent my frustration but rather to indicate it was not a showstopper but merely an inconvenience.

Regarding locale, the doc indicates that this prop is on the provider, but is seems to be on the Messenger component itself.

I'm all for helping with a PR, but seems like updating the readme would go a long way and I would def need a review from someone understanding the library better.

**Comment by benschwarz** [comment]
> Regarding locale, the doc indicates that this prop is on the provider, but is seems to be on the Messenger component itself.

Great, thanks for the clarification. I agree, looks like a `README` update will fix that. 

> I'm all for helping with a PR, but seems like updating the readme would go a long way and I would def need a review from someone understanding the library better.

No problem, happy to assist you in getting the PR completed.

**Comment by robmorieson** [comment]
Thanks for raising these issues @IngoVals, happy to report that our Typescript definitions have been improved in the latest release ([2.8.0](https://github.com/calibreapp/react-live-chat-loader/releases/tag/2.8.0)) and [README has been updated](https://github.com/calibreapp/react-live-chat-loader#user-content-messenger) to match ✅
