### ISSUE TITLE
[Bug] Button stops working

### ISSUE THREAD

**Issue by rumfiske** [calibreapp/react-live-chat-loader#128]
Button stops to work if you click it, and close the chat window, navigate to new page. And now try to open it again, it doesn't work anymore.

My setup (ChatWoot)
![Code_FgM44oQJ7r](https://user-images.githubusercontent.com/59709554/164998490-010a123d-285f-4dc1-bd9a-2dc82ab8c292.png)

**Comment by robmorieson** [comment]
Hey @rumfiske we’re unable to replicate this issue, so closing for now in the hopes it has been resolved on ChatWoot’s end. We’ll happily reopen if you have any further info or a demo.
