### ISSUE TITLE
How do you start the app after cloning?

### ISSUE THREAD

**Issue by cmstroscio** [calibreapp/react-live-chat-loader#129]
Trying to start a server to see the app in action. I've cloned it and and npm installed. I don't see a script for how to start  the app.

**Comment by benschwarz** [comment]
Hey @cmstroscio, apologies for the delay in getting back to you. 

[The demo website](https://react-live-chat-loader.now.sh/) is a next.js site. It resides in the `website` directory of this repository. As you'll see from the `package.json` file within that directory, there's three tasks you can run: 

* `npm run dev` (run a local server on port 5000)
* `npm run build` (run next build)
* `npm run start` (run next start)

I'll leave this issue open as a reminder to document this in the project README. Thanks for asking!

**Comment by cmstroscio** [comment]
Thank you,
Marshall

**Comment by robmorieson** [comment]
Steps on launching the demo website have been [added to the README](https://github.com/calibreapp/react-live-chat-loader#%EF%B8%8F-examples). Thanks for bringing this gap in our docs to our attention, @cmstroscio 📝
