### ISSUE TITLE
Is that possible to pass user info with initializing of live-chat module?

### ISSUE THREAD

**Issue by w3fullstack** [calibreapp/react-live-chat-loader#133]

**Comment by benschwarz** [comment]
@w3fullstack That's not something that's build into react-live-chat-loader, however, you may be able to achieve this based on whichever product you are using. 

For example, Intercom relies on a window object (`window.intercomSettings`) to share user data. I'd recommend checking the documentation of your provider directly. 

react-live-chat-loader will load your third party code after first-party code has initialized, so if there's support within your chat product, then it should work a-ok. Hope that helps!
