### ISSUE TITLE
[Bug] Doesn't works with React 18

### ISSUE THREAD

**Issue by aaron5670** [calibreapp/react-live-chat-loader#137]
**First, I want to thank you so much for this library! I enjoy using this.**
 Unfortunately, this library does not work with React 18.

## Package.json
![image](https://user-images.githubusercontent.com/17295145/171931836-3fbb33a8-f154-4515-b255-758299e5d756.png)

## Describe the bug
Please provide a clear and concise description of what the bug is. Include relevant operating system, browser and other environment information.

## How To Reproduce

1. Make sure you are on React 18.x.
2. Make sure you have the latest version of react-live-chat-loader (2.7.3).
3. npm install
4. See error bellow

## Expected behaviour
A clean npm install

## Screenshots
![image](https://user-images.githubusercontent.com/17295145/171932220-5bb6a6c4-20d8-41a5-a977-5acde4b5e656.png)

**Comment by benschwarz** [comment]
Hey @aaron5670, no the library isn’t dead, we’re busy and not using React 18 ourselves. 

React 18 is version excluded in package.json. Updating that is maybe all that’s required to resolve this issue. If you find yourself with the time to explore it I’d be happy to review and merge.

**Comment by aaron5670** [comment]
Hi @benschwarz, thank you!
I will look at it if I can find some time. :)
