### ISSUE TITLE
How to use this for a Webflow website

### ISSUE THREAD

**Issue by Jitao-Hu** [calibreapp/react-live-chat-loader#139]
Hello,

I am using Webflow to create my website and google tag manager to make drift works. But I am not sure how to install this inside the google tag manager since npm seems does not work inside the google tag manager.

Thank you ahead for your help!

**Comment by benschwarz** [comment]
Hey @Jitao-Hu, 

This library must be integrated with your React project. Once it's added to your site, react-live-chat-loader will then load Drift itself. It won't be compatible with Google Tag Manager. Sorry for the bad news!
