### ISSUE TITLE
[Bug] CORS ISSUE with messenger

### ISSUE THREAD

**Issue by raymonnguyen** [calibreapp/react-live-chat-loader#214]
### Describe the bug

I'm having CORS issue when call messenger-sdk, do you have any ideas how I can whitelist it? I also fill out the domain in the developer dashboard but the issue still there. Really appreciate your help

### Screenshots

<img width="739" alt="Screen Shot 2022-12-19 at 17 17 59" src="https://user-images.githubusercontent.com/115201589/208402909-5d8e086b-8361-4b78-923d-62a1a7ea7e83.png">
<img width="758" alt="Screen Shot 2022-12-19 at 17 18 10" src="https://user-images.githubusercontent.com/115201589/208402929-0814178f-5919-4b48-b4d1-6d21cbadbe96.png">
<img width="990" alt="Screen Shot 2022-12-19 at 17 19 27" src="https://user-images.githubusercontent.com/115201589/208403164-70bf638a-52ba-4012-ad5c-a8b940f82f15.png">

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by robmorieson** [comment]
Hi @raymonnguyen — CORS errors generally indicate an issue with domain configuration in Facebook, which requires a domain to be safe-listed, publicly accessible (i.e. no `localhost`) and served over `HTTPS`. [ngrok](https://ngrok.com/) can be helpful in achieving this locally. 

Closing this one as it doesn’t appear to be a bug in the package (you can see the Messenger provider loading without issue on our [demo website](https://react-live-chat-loader.vercel.app/messenger)) but rather an implementation issue to be solved on Facebook’s side.
