### ISSUE TITLE
Messenger not working

### ISSUE THREAD

**Issue by FateXRebirth** [calibreapp/react-live-chat-loader#22]
@michaeldijkstra thanks for adjusting messenger provider and component first!

I used the latest version in my project, but no customer chat dialog pop up, Have you test it?
I know you move `fb-customerchat` from preload phase to a component called `CustomerChat`,
it seems not working, we know that `fb-customerchat` is necessary for Customer Chat SDK, I think the problem is when you finish loading script, then `state` will become `complete`, then `LiveChatLoaderContext` will update which will trigger useProvider update as well, then re-render  
`CustomerChat`, in the same time,  Customer Chat SDK is parsed and executed, it tries to find the `fb-customerchat`, but `CustomerChat` just render, so it can't find any match, so it won't work.
I try to move `fb-customerchat` to any place except inside of `LiveChatLoaderProvider`, it works as expected.

Is not convenient to have to write additional code for using react-live-chat-loader, What if we wrap code which creates `fb-customerchat` in `useEffect` of Messenger component? I think this a great way to decouple all code in load script and still work as you want and you did before.

by the way, I would like you to help me delete this PR: https://github.com/calibreapp/react-live-chat-loader/pull/10, that was a mistake. please delete it.

**Comment by michaeldijkstra** [comment]
@FateXRebirth Thanks for following up on this.

I've just created PR #23 which should fix the issue. Rather than `useEffect` I moved the `useContext` out of the component and opted for `React.memo` to ensure it only renders once.

As for PR #10 I don't believe I can delete it, but it has been closed so there's nothing to do there!

**Comment by FateXRebirth** [comment]
@michaeldijkstra Great to heard that! I tested it, it works perfectly, thanks for doing that. 👍 

Can you help me adjust this ?
https://github.com/calibreapp/react-live-chat-loader/pull/11#discussion_r390098110

**Comment by michaeldijkstra** [comment]
> Can you help me adjust this? #11 (comment)

👍Updated my latest PR, this will go out in the next release!
