### ISSUE TITLE
[Feature Request] Intercom icon

### ISSUE THREAD

**Issue by niallobrien** [calibreapp/react-live-chat-loader#241]
### What problem would this feature solve?

Hi, I'm wondering how I can change the Intercom placeholder icon/image to a custom one? Many thanks.

### Describe the solution you’d like to see

I'd like to know how I can customise the placeholder icon/image for the Intercom Live Chat feature.

### Are you willing to work on implementing this solution?

Yes

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
Hey @niallobrien

Thanks for logging — I'm not super familiar with every products full list of options, so I did some research and found these references: 

* [How can I change the messenger logo?](https://forum.intercom.com/s/question/0D52G00004Q2NiSSAV/how-can-i-change-the-messenger-logo)

> If you’re a Premium or Scale customer, you can add a custom logo for the Messenger instead of the default logo.

> Alternatively, you can also create a “custom launcher”

* [Create a custom launcher](https://www.intercom.com/help/en/articles/2894-create-a-custom-launcher)
* [Hide the Intercom launcher](https://www.intercom.com/help/en/articles/189-hide-the-intercom-messenger-launcher)

Out of interest, which of these two options are you using?

If you're keen on working on this enhancement, we'd be happy to review and merge.

**Comment by niallobrien** [comment]
Hi @benschwarz - thanks for your reply. I had to reach out to my team to see what way they had Intercom setup. It turns out that they had another workspace setup for dev access, and this workspace had different settings for Messenger (brand colours, icon etc.). I'll take some time this week to take another look at replacing the current implementation with Live Chat Loader and will keep you posted. Many thanks!

**Comment by benschwarz** [comment]
Ah yes, the dark grey Intercom logo signifies "dev workspaces", but react-live-chat-loader only has the blue default icon that Intercom use by default.
