### ISSUE TITLE
[Bug] Intercom seems not to work on NextJS 13

### ISSUE THREAD

**Issue by colenh** [calibreapp/react-live-chat-loader#261]
### Describe the bug

In development, it works fine. However, in a production environment (https://porcify.com/), it seems to not work at all. When hovering the icon, the following error occurs.
![image](https://user-images.githubusercontent.com/40342475/233859795-b4eef9e6-c92a-452a-83ec-31ab2c2c50ca.png)

### How To Reproduce

1. open your browser console
2. hover over the intercom widget on https://porcify.com/

### Relevant Log Output

```shell
Uncaught TypeError: can't access property "parentNode", r is undefined
    NextJS 32
        m
        m
        v
        h
        onMouseEnter
        l2
        l7
        sn
        sn
        sr
        ss
        uM
        ih
        ss
        iU
        iA
        so
        sa
        si
        si
        createRoot
        hydrate
        4744
        r
        appBootstrap
        4744
        d
        n
        <anonymous>
        O
        c
        <anonymous>
```

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by SamSaprykin** [comment]
hey @colenh, did you find solution for Next 13?

**Comment by colenh** [comment]
sadly not, i had to move to react-use-intercom

**Comment by ChezMose** [comment]
Just sharing, but I just installed react-live-chat-loader with next 13.4.2 + Intercom and it worked perfectly.
I use the app router + the [lang] folder.

**Comment by SamSaprykin** [comment]
yep, works well for me as well:

`"next": "13.4.5"`
`"react-live-chat-loader": "^2.8.1"`

**Comment by benschwarz** [comment]
Thanks for your notes @ChezMose and @SamSaprykin. Seeing as you've had it working I'm going to go ahead and close this issue.
