### ISSUE TITLE
Intercom controls which pages it shows on

### ISSUE THREAD

**Issue by moshie** [calibreapp/react-live-chat-loader#27]
I imagine this will be quite difficult to solve but here goes..

Intercom's admin panel can control on which pages to display the chat widget.

As developers by adding the `<Intercom />` component to certain pages we lose the flexibility of having our support team manage which pages to display the widget.

**Comment by michaeldijkstra** [comment]
Hey @moshie — Unfortunately I don't have access to an account with that feature (it's a Pro upgrade) so would you mind linking me to pages on your site where it has been turned on and off? I'd like to see how it behaves to understand if there's anything we can do to support this …

**Comment by moshie** [comment]
Hey @michaeldijkstra 

Hope the below helps.

Not enabled: https://www.zopa.com/
Enabled: https://www.zopa.com/contact

It's worth mentioning the pages which have the chat disabled still request the intercom scripts.

**Comment by michaeldijkstra** [comment]
Thanks, @moshie.

Would an option to hide the placeholder work in this situation? Then Intercom would load when idle and decide to show or not based on the settings within Intercom.

**Comment by moshie** [comment]
@mikeydijkstra 

Not so sure that would as the developer would be responsible for determining what page the placeholder should show / hide, taking the control away from the intercom admin panel.

I did get in touch with intercom and they mentioned that they do not offer an api for this functionality which is a shame 👎

**Comment by benschwarz** [comment]
Seeing as this is a server-side based control and there's also no API, it sounds like there's nothing to be done from the perspective of this library.
