### ISSUE TITLE
Beacon shown twice on iPhone

### ISSUE THREAD

**Issue by zamirkhan** [calibreapp/react-live-chat-loader#29]
Let me preface this by saying I do not know much about this issue, other than I've had multiple users report it. I do not know if it is HelpScout or this package, but it seems it might be more widespread if it was HelpScout and I could not find any sign of it when searching.

I've had some users, all on iPhones, report that the Beacon shows up twice on some page loads. See this image: 
<img width="270" alt="Screen Shot 2020-04-24 at 3 22 10 PM" src="https://user-images.githubusercontent.com/2654175/80249313-97704380-863f-11ea-9107-12c80ee66d5d.png">

When this happens, they also report some kind of loss of functionality on the page itself. This makes me think there has been some sort of javascript error impeding the app. I know these types of issues are very difficult to track down and I don't have a small repro scenario (nor currently the resources to craft one), but I thought I should post this here in case anyone has an idea what might be going on.

**Comment by mikedijkstra** [comment]
@zamirkhan Thanks for letting us know.

Do both beacons stay on the page the whole time? Do you have a URL we could look at?

**Comment by benschwarz** [comment]
@zamirkhan, I'll assume this issue got figured out back in April. LMK if that's not the case. 👍
