### ISSUE TITLE
[Feature Request] Implementing FrontChat Provider

### ISSUE THREAD

**Issue by IlirEdis** [calibreapp/react-live-chat-loader#344]
### What problem would this feature solve?

Implement FrontChat Provider

### Describe the solution you’d like to see

While trying to add [FrontChat](https://dev.frontapp.com/docs/chat-sdk-reference) as a new provider i get `Uncaught TypeError: window.FrontChat is not a function` even though `FrontChat` script is loaded and added to the `window` object.

Heres my fork: https://github.com/IlirEdis/react-live-chat-loader

and below some screenshots of the error:

<img width="1692" alt="Screenshot 2023-11-27 at 10 46 41" src="https://github.com/calibreapp/react-live-chat-loader/assets/128377763/16f4f076-7dc9-43aa-8e66-7ac88e4049b0">

<img width="1692" alt="Screenshot 2023-11-27 at 10 46 56" src="https://github.com/calibreapp/react-live-chat-loader/assets/128377763/817af819-bd5d-4d5d-aef3-05066d3f7c88">

### Are you willing to work on implementing this solution?

Yes

### Additional context

I'd like to have your help on implementing FrontChat as a new provider if you like to, of course. 

Also after we finish this i'd like to contribute on updating Nextjs to the latest version with AppRouter.

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
Hey @IlirEdis, happy to help debug and get your contribution eventually merged. Could you create a pull request? That way there will be a preview deployment of the preview website, which we can use to debug.

Have you verified that the script is being loaded correctly?

**Comment by IlirEdis** [comment]
Hi @benschwarz, just noticed i wasn't loading the script properly. 
Thanks for the hint! Now it works as i am noticing.
Please review my code and let me know then i will get back to style the icon.
PR created.

**Comment by robmorieson** [comment]
@IlirEdis thanks for your work on getting Front support added 🙌 

Happy to report that #345 is out with our latest release (2.9.1)
