### ISSUE TITLE
[Bug] Uncaught SyntaxError: Unexpected token '.' in Chrome < 80

### ISSUE THREAD

**Issue by valentinfily** [calibreapp/react-live-chat-loader#358]
### Describe the bug

- When loading a page using `react-live-chat-loader` with Chrome < 80 we encounter exception `Uncaught SyntaxError: Unexpected token '.'`
- I am using `2.8.2`.

### How To Reproduce

This Chrome 79 emulated browser will help with reproduction : https://www.browserling.com/browse/win10/chrome79/https://react-live-chat-loader.vercel.app/helpscout

### Screenshots

Error in console :
<img width="1019" alt="image" src="https://github.com/calibreapp/react-live-chat-loader/assets/6137770/12de2bd5-de82-4dad-9a09-9d344250f827">
<img width="553" alt="image" src="https://github.com/calibreapp/react-live-chat-loader/assets/6137770/3220dbf9-3fc6-4ad0-bb72-0c08b66352d6">

Exception caught in Sentry in my own app :
<img width="886" alt="image" src="https://github.com/calibreapp/react-live-chat-loader/assets/6137770/8b16fba1-dabd-40c9-89be-d841a6499ee8">

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
Thanks for logging @valentinfily

While we don't have a documented browser support statement for this project, Chrome 79 is ~4 years old and safe navigation operator is part of ES2020. We're unlikely to change the library for this. 

Assuming you're using some form of bundler, you may need to update the build target.

**Comment by benschwarz** [comment]
Having said that, we're going to tag a new release of RLCL which will include #341… which will likely address the issue that you've observed @valentinfily. Hang tight, release should be in the next few days.

**Comment by valentinfily** [comment]
@benschwarz any update on this potential release ? 🙏

**Comment by robmorieson** [comment]
Hi @valentinfily happy to announce that the update Ben mentioned above (#341) has been included in our latest release (2.91) and confirming via the Browserling link above that the issue you reported has been resolved.
