### ISSUE TITLE
[Bug] Release 2.9.0 Empty Build Contents

### ISSUE THREAD

**Issue by samc** [calibreapp/react-live-chat-loader#370]
### Describe the bug

Latest release (2.9.0) is shipping with an empty build, file contents include:

- README.md
- package.json
- LICENSE

### Screenshots

<img width="156" alt="Screenshot 2024-01-09 at 11 43 23 AM" src="https://github.com/calibreapp/react-live-chat-loader/assets/11219061/f8e80869-0fce-4069-873b-b001483f5e2a">

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by robmorieson** [comment]
@samc thanks for reporting.  This has been fixed with our latest patch release (2.9.1)
