### ISSUE TITLE
Suggestion: Add Drift Widget

### ISSUE THREAD

**Issue by mirshko** [calibreapp/react-live-chat-loader#4]
I'm sure its already in the pipeline for this package, but adding [Drift](https://www.drift.com/) messenger support would be awesome as well!

<img width="203" alt="Screen Shot 2019-12-02 at 12 21 50" src="https://user-images.githubusercontent.com/8116716/69955634-66f80380-14fe-11ea-81f4-d62a8aa31336.png">

**Comment by micdijkstra** [comment]
Hey @mirshko, thanks for logging this.

We’re not using Drift and have no reason to add it to the library ourselves. Do you think this is something you’d be interested in contributing to the library?

We've added details for [Adding a provider](https://github.com/calibreapp/react-live-chat-loader#adding-a-provider) to the README and we’d be happy to coach you through the PR process.

**Comment by mirshko** [comment]
For sure! 

It looks like the Drift widget has a line that send the version of the Drift snippet to the widget for analytics, I presume this is something we should just keep an eye on should the production Drift snippet change?

I'm fairly sure this is needed or at least common practice, I could reach out to a Drift engineer for some advice on this as well as needed.

PR Incoming. 

<img width="200" alt="Screen Shot 2019-12-03 at 09 54 02" src="https://user-images.githubusercontent.com/8116716/70035283-daf3e380-15b2-11ea-89af-91bdf4dcf426.png">
