### ISSUE TITLE
Option to hide the intercom widget icon on specific pages

### ISSUE THREAD

**Issue by junaidalphasquad** [calibreapp/react-live-chat-loader#404]
### What problem would this feature solve?

Hide the icon on any web page based on any condition.

### Describe the solution you’d like to see

There should be an option similar to what Intercom provides for their users, allowing them to hide the default launcher by setting the "hide_default_launcher" config to true.

I would like to see that passing "true" to `hide_icon` hides the Intercom icon.

### Are you willing to work on implementing this solution?

No

### Code of Conduct

- [x] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
@junaidalphasquad thank you for raising this issue. 

RLCL's primary aim is to augment the load process for live chat implementations. As such there isn't much appetite on my side to implement or support all features of any single implementation. 

In this case I think the best path forward for your project will be to add logic and not include chat in those circumstances.
