### ISSUE TITLE
Plans on adding type definitions?

### ISSUE THREAD

**Issue by kgoedecke** [calibreapp/react-live-chat-loader#45]
This project is amazing and we are currently adding it to our own website.

I was wondering if you have any plans on adding type definitions?

Cheers

**Comment by mikedijkstra** [comment]
Hi @kgoedecke,

Yes we'd like to add type definitions (and even explore converting the library to Typescript). Do you think this is something you’d be interested in contributing to the library?

**Comment by CodyBrouwers** [comment]
I'm using this great package with Intercom so I wrote these definitions. Just be sure to include the file in your `tsconfig.json` `includes` array.

`react-live-chat-loader.d.ts`
```ts
/// <reference types="react" />

declare module "react-live-chat-loader" {
  interface IProviderProps {
    provider: "intercom";
    providerKey?: string;
  }

  export class LiveChatLoaderProvider extends React.Component<IProviderProps> {}

  interface IIntercomProps {
    color?: string;
  }

  export class Intercom extends React.Component<IIntercomProps> {}

  type TOpen = ({ open }: { open: boolean }) => void;

  export function useChat({ loadWhenIdle: boolean }): [string, TOpen];
}

```

**Comment by mikedijkstra** [comment]
The project has been ported to Typescript so I'll close this as you can get definitions from the package.
