### ISSUE TITLE
Are messages delivered to the client if he doesn't open the chat?

### ISSUE THREAD

**Issue by kgoedecke** [calibreapp/react-live-chat-loader#47]
I'm wondering if the user switches to a new page if he will receive messages that our support team writes? I believe they won't be since the widget is only loaded once the user hovers that mouse over the icon?

Any advice on how to overcome this?

**Comment by benschwarz** [comment]
If you're wanting chat to load when the browser has become idle (thus not blocking your page from its own initialisation), then I'd recommend checking out the idlePeriod option.

This way chat will be initialised without blocking user tasks and incoming messages will be fetched also

**Comment by benschwarz** [comment]
Of course if the user mouses over the chat it'll be attempted to be loaded immediately 👍

**Comment by kgoedecke** [comment]
Ah perfect. I guess that answers the question 🙏 thanks Ben.
