### ISSUE TITLE
Ability to set user attributes

### ISSUE THREAD

**Issue by josiahwiebe** [calibreapp/react-live-chat-loader#48]
Using Intercom, you're able to set user data when registering the chat loader. For example:

```js
window.Intercom('boot', {
app_id: 'app_id_here',
...(user && {
  name: `${user.name.first} ${user.name.last}`,
  email: user.email,
  user_id: user.id,
  created_at: user.created_at,
}),
```

Is there any way to do this with this loader currently?

**Comment by benschwarz** [comment]
Hey @josiahwiebe 👋 

You can achieve this by using `window.intercomSettings` ([See docs here](https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects#section-data-attributes)).

Bear in mind that any `window.intercomSettings` Messenger Attributes won't be applied to `react-live-chat-loader`.

Hope that helps! Let me know if that's not quite what you're after.

**Comment by josiahwiebe** [comment]
Yep, I ended up using `window.Intercom` in a `useEffect` hook. Thanks for this great library!

**Comment by benschwarz** [comment]
Great, glad it worked out. 

Tell your friends 👍
