### ISSUE TITLE
Suggestion: Add Messenger Customer Chat Plugin

### ISSUE THREAD

**Issue by dlackty** [calibreapp/react-live-chat-loader#5]
Facebook Messenger also provides [a customer chat plugin](https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin) which is common to consumer-facing services.

**Comment by micdijkstra** [comment]
Hey @dlackty, thanks for logging this.

We’re not using Facebook Messenger and have no reason to add it to the library ourselves. Do you think this is something you’d be interested in contributing to the library?

We've added details for [Adding a provider](https://github.com/calibreapp/react-live-chat-loader#adding-a-provider) to the README and we’d be happy to coach you through the PR process.

**Comment by dlackty** [comment]
Hello, @michaeldijkstra 
Our team is working on adding a provider, and we faced an API design issue and would like to hear from you.

The background: 

Messenger Customer Chat plugin requires two parameter to setup: app id and fan page id

The issue:

Current design of react-live-chat-loader only has one `providerKey` prop to use.

Suggestions:
1. Let `providerKey` to receive an object
2. Add another prop for this case

**Comment by michaeldijkstra** [comment]
Hey @dlackty — Great to hear you're working on Facebook Messenger provider!

Without breaking the existing API, I think we could allow provider developers to pass through additional props as required. I believe we can just do this in `src/index.js` and pass all additional props using the spread operator. By passing them this way we should be able to support additional provider requirements without further API changes in the future.

What do you think?

**Comment by dlackty** [comment]
@michaeldijkstra My colleague just sent an PR #11. Please have a look, thank you!

**Comment by michaeldijkstra** [comment]
This has been merged and released in version 2.0! 🚀
