### ISSUE TITLE
Provider for crisp.chat?

### ISSUE THREAD

**Issue by karlhorky** [calibreapp/react-live-chat-loader#54]
Hi there, first of all, thanks for the amazing component, this is great! Anything that can help load less JavaScript on the client is awesome! 💯

I wanted to ask whether it would be possible to have a provider for [Crisp chat](https://crisp.chat/en/), since Intercom and Drift are supported.

**Comment by benschwarz** [comment]
Hey @karlhorky 🙋‍♂️

Thanks for the kind words! 

We generally don't add support for services we're not using ourselves, but if you'd like to take a shot at writing the implementation, we'd be happy to coach you and get it merged. 

If that's something you'd like to try, I'd recommend checking the README, where you'll find instructions for how to add a provider. 

If you run into any snags along the way be sure to let us know.

**Comment by benschwarz** [comment]
Closing this issue for now, feel free to leave comments or upvotes here.

**Comment by pbteja1998** [comment]
Hey @benschwarz, I am also using Crisp chat. Would love to have support for this. Is it ok if I work on this?

**Comment by pbteja1998** [comment]
For reference, this is the code that I have to add to initialize crisp chat. 

```js
window.$crisp = [];
window.CRISP_WEBSITE_ID = "MY_CRISP_WEBSITE_ID";

(function () {
	d = document;
	s = d.createElement("script");
	s.src = "https://client.crisp.chat/l.js";
	s.async = 1;
	d.getElementsByTagName("head")[0].appendChild(s);
})();
```

To open chatbox programmatically, I have to do `$crisp.push(['do', 'chat:open'])` and to close it, I have to do `$crisp.push(["do", "chat:close"])`

Would something like this work for `react-live-chat-loader`?

**Comment by mikedijkstra** [comment]
Hi @pbteja1998 — Yes we'd love to see a PR adding crisp chat.

Please see the [README](https://github.com/calibreapp/react-live-chat-loader#adding-a-provider) for details on adding a provider and use the other files as a reference.

We no longer close the chat, but do open it. The other thing to make it work smoothly is detecting when the provider has fully loaded so we can remove the fake widget. Do you know if Crisp have a callback you can hook into for this?

**Comment by pbteja1998** [comment]
Yes, I think `session:loaded` callback would work here.

[Reference](https://help.crisp.chat/en/article/how-to-use-crisp-javascript-sdk-10ud15y/#2-register-a-callback-on-event)

**Comment by benschwarz** [comment]
Hey @pbteja1998, are you still interested in taking this PR on? We'd be happy to help you step through any roadblocks in getting it together.

**Comment by pbteja1998** [comment]
Hey @benschwarz. Unfortunately, I won't be taking up this PR anytime soon. So, you can go ahead and close this issue if you want.

**Comment by benschwarz** [comment]
No problem at all @pbteja1998, thanks for letting me know 👍
