### ISSUE TITLE
Getting Error: Invalid hook call. 

### ISSUE THREAD

**Issue by motiko** [calibreapp/react-live-chat-loader#71]
Hi, I'm trying to add a new provider.
following the instructions [to add an example page](https://github.com/calibreapp/react-live-chat-loader#4-add-an-example-page)
i get the error 
> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. 
any idea what i'm doing wrong?

**Comment by mikedijkstra** [comment]
Hi @motiko,

Can you please provide extra detail or code snippets? Without knowing what you've done it's difficult to diagnose the issue.

**Comment by mikedijkstra** [comment]
@motiko You are probably running into the duplicate versions of React error which you can solve by following the instructions in the README (unfortunately this can be fiddly sometimes):

***

To create the distribution version and reference it, do the following:

In the root of the project, run npm run build to build the package into dist
Update website/package.json to reference the dist build: "react-live-chat-loader": "../"
In the website directory run npm install
In the website directory run the server with npm run dev
Add a new page to website/pages/ which includes the new component
Add a link to the provider in website/pages/index.js
Add a link to the provider in website/components/exampleLinks.js

***

**Comment by motiko** [comment]
hi,
this is exactly the steps i follow
```sh
$ npm install 
$ npm run build
$ cd website
$ git diff
...
-    "react-live-chat-loader": "2.4.1"
+    "react-live-chat-loader": "../"

```
and finally
```sh
$ npm install
$ npm run dev
```
im on main branch without any changes.  
any clue what is causing this?

**Comment by benschwarz** [comment]
Hey @motiko, could you also share the provider code that you've written?

**Comment by motiko** [comment]
I will provide in next comment.
It is important to note i run into this error without any code changes (i've stashed them for now)
Might be an `npm` version issue?

**Comment by motiko** [comment]
adding the exact error for completness

```
../module/components/LiveChatLoaderProvider.js (22:36) @ LiveChatLoaderProvider

  20 |       props = _objectWithoutProperties(_ref, ["provider", "children", "idlePeriod"]);
  21 | 
> 22 |   const [state, setState] = useState('initial');
     |                                    ^
  23 | 
  24 |   const value = _objectSpread({
  25 |     provider,
```

**Comment by motiko** [comment]
Can you share which `node` and `npm` version i should use when building this?

**Comment by mikedijkstra** [comment]
@motiko I have just made an update to make the versions of react the same in the web and library projects. Please try rebasing from this. If that doesn't work you could also try `npm link` as [described here](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react).

**Comment by motiko** [comment]
Thank you! It solved the issue.
- Would it make sense to pin react version in both folders? (to prevent this collision in the future)
- Probably should update the README since `website/package.json` now has  `"react-live-chat-loader": "../"` by default (remove following step )
> Update website/package.json to reference the dist build: "react-live-chat-loader": "../"

**Comment by mikedijkstra** [comment]
@motiko Sorry that should never have made it to GitHub. We can't reference it relatively during the build. I've just fixed this on main.

**Comment by mikedijkstra** [comment]
We now build the library and the website together which should fix this issue. If anyone runs into this issue again please try linking react in the library with react in the website directory: `npm link react website/node_modules/react`
