### ISSUE TITLE
Bundled type definitions have broken imports

### ISSUE THREAD

**Issue by ridem** [calibreapp/react-live-chat-loader#77]
Thanks for this great library!

It seems like the imports in the bundled type definitions are broken.
For example, at https://unpkg.com/browse/react-live-chat-loader@2.4.1/dist/components/LiveChatLoaderProvider.d.ts, `provider` resolves to `any` because your absolute import settings (`baseUrl`) aren't used to create relative paths when declarations are created.

I don't know of any solution that wouldn't involve adding another package to your build toolchain. Potentially interesting without adding webpack or a full rollup setup:
- https://github.com/zerkalica/zerollup/tree/master/packages/ts-transform-paths
- https://github.com/justkey007/tsc-alias

**Comment by mikedijkstra** [comment]
This has been released in 2.5.1
