### ISSUE TITLE
Thanks for the inspiration!

### ISSUE THREAD

**Issue by danielbachhuber** [calibreapp/react-live-chat-loader#87]
Just wanted to give you a heads up that I've adapted the Intercom chat widget to a pure JavaScript implementation (my first JS library, too) https://github.com/danielbachhuber/intercom-facade

We're not using React, so I wanted to do something super plain and simple.

**Comment by benschwarz** [comment]
Hey @danielbachhuber! 

Thanks for sharing. Glad to hear this approach worked well for you. Congrats on writing your first JS library too! ✨ 

Originally we were considering writing `react-live-chat-loader` as a vanilla JS library, but seeing as we were using React ourselves, it made the most sense to write it in React. All the same, I'm glad to see your implementation. Kudos to you!
