### ISSUE TITLE
Warning: The final argument passed to useEffect changed size between renders

### ISSUE THREAD

**Issue by zamirkhan** [calibreapp/react-live-chat-loader#9]
I get this warning from time to time.

```
Warning: The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant.

Previous: []
Incoming: [function () {
    // Don't load if idlePeriod is 0, null or undefined
    if (typeof window === 'undefined' || !loadWhenIdle || !idlePeriod) return; // Don't load if 2g connection or save-data is enabled

    if (connection && (connection.saveData || /2g/.test(connection.effectiveType))) return;
    var idleThreshold = parseInt(idlePeriod, 10);
    if (isNaN(idleThreshold)) return; // deadline.timeRemaining() has an upper limit of 50 milliseconds
    // We want to ensure the page has been idle for a significant period of time
    // Therefore we count consecutive maximum timeRemaining counts and load chat when we reach our threshold

    var elapsedIdlePeriod = 0;
    var previousTimeRemaining = 0;

    var scheduleLoadChat = function scheduleLoadChat(deadline) {
      if (elapsedIdlePeriod > idleThreshold) return loadChat({
        open: false
      });
      var timeRemaining = deadline.timeRemaining(); // To ensure browser is idle, only accumalte elapsedIdlePeriod when
      // two consecutive maximum timeRemaining's have been observed

      if (previousTimeRemaining > 49 && timeRemaining > 49) elapsedIdlePeriod += timeRemaining;
      previousTimeRemaining = timeRemaining;
      requestIdleCallback(scheduleLoadChat);
    };

    if (requestIdleCallback) {
      requestIdleCallback(scheduleLoadChat);
    } else {
      setTimeout(function () {
        return loadChat({
          open: false
        });
      }, idleThreshold);
    }
  }]
    in HelpScout (at App.js:908)
    in LiveChatLoaderProvider (at App.js:902)
    in Provider (at App.js:966)
...
```

**Comment by michaeldijkstra** [comment]
Hey @zamirkhan — Thanks for logging this. Can you provide extra context around when this warning is firing?

**Comment by zamirkhan** [comment]
Hi @michaeldijkstra. I observe this in my development environment in the console when using this package. Right now it appears to be happening every time, a few seconds after page load, without me taking any action. The timing makes me think it's happening when the control believes the page to be idle (and thus starts loading) and the stack trace would appear to support that. The warning happens in both Chrome and Safari.

**Comment by benschwarz** [comment]
Just checking back on this @zamirkhan, did you manage to solve this or is it an ongoing issue?

**Comment by zamirkhan** [comment]
Thanks for checking @benschwarz . Is it possible that this was addressed after `2.1.1`? We were still seeing it, but I just tried our `2.1.3` and am not seeing it yet.

**Comment by benschwarz** [comment]
I'm not entirely sure. I don't believe we've had this issue ourselves. If you're able to provide the details that @mikedijkstra  required earlier we can help to assess and potentially fix the issue.

**Comment by zamirkhan** [comment]
I think I provided all the details we possibly could on March 3rd. It's a strange one because it's trivial for me to reproduce (happens 100% of the time), but apparently not for others. It's not a show-stopper; just annoying during development to see an error in the console. However if it disappears as mysteriously as it appeared simply by updating, then I'm fine with that.

**Comment by benschwarz** [comment]
@zamirkhan To confirm, are you still seeing this issue on the latest version? If so I'd consider this a closable issue.

**Comment by zamirkhan** [comment]
I agree this is closeable for now. We did not see it in the updated version. Thank you.
