### ISSUE TITLE
Chat-loader not working for facebook.

### ISSUE THREAD

**Issue by EmmanuelManana** [calibreapp/react-live-chat-loader#91]
When trying to use the facebook  provider="messenger" and providerKey="17**274**3013379" (application ID) I get 

=>  Refused to display 'https://www.facebook.com/' in a frame because it set 'X-Frame-Options' to 'deny'.

I have white listed the domain from which I using the "react-chat-loader" package.

**Comment by mikedijkstra** [comment]
@EmmanuelManana Can you confirm if you're using localhost or a hosted domain? Facebook Messenger will not load on localhost. I had quite a few issues when implementing it locally.

We are using the latest version of `react-live-chat-loader` on our demo page and it's [loading correctly](https://react-live-chat-loader.vercel.app/messenger) so I'm going to close this issue as this looks like an implementation problem and not a problem with the package.
