### ISSUE TITLE
[Feature Request] Ability to style components

### ISSUE THREAD

**Issue by taijuten** [calibreapp/react-live-chat-loader#92]
## What problem would this feature solve?
Currently Intercom allows certain positional changes. It is not possible to mirror this, since the `<Intercom>` component uses hard-coded styling, other than the color

## Describe the solution you’d like to see
Ability to pass in a style object to override any defaults

**Comment by mikedijkstra** [comment]
Hi @taijuten — Thanks for logging this issue.

Ideally we'd like to make our component APIs the same as the provider APIs so you can almost just copy/paste the settings. In addition to this it's easier to manage responsive behaviour inline with how the provider behaves.

Looking at the [Intercom Docs](https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects#section-messenger-attributes) it seems we should add support for:

- alignment:  "left" or "right" (default to right)
- vertical_padding: Minimum value of 20, not used on mobile
- horizontal_padding: Minimum value of 20, not used on mobile

Is this something you'd like to contribute to the package? If so we can help you work through a PR.

**Comment by benschwarz** [comment]
@Undistraction thank you for sharing this feedback. 

The z-index is set 1 higher than wha intercom's official widget uses. 

That way, intercom loads and appears underneath the faux widget, which is then hidden.

I have no qualms with adding style attribute support, but it's worth noting that you'd still have to override intercoms widget too. 

What do you think?

**Comment by Undistraction** [comment]
@benschwarz I think adding an id to the placeholder button (and/or accepting a style object) would provide a lot of flexibility to consumers of this package with relatively minimal change your end.

**Comment by Undistraction** [comment]
In fact, I think adding an `id` is definitely worthwhile because it would allow both elements to be styled at the same time:
```
.live-chat-loader-placeholder,
.intercom-container {
  z-index: XXX;
}
```
