### ISSUE TITLE
[Feature Request] Accept Drift Event Handlers

### ISSUE THREAD

**Issue by myleslinder** [calibreapp/react-live-chat-loader#93]
## What problem would this feature solve?
Drift allows you to respond to a [number of events](https://devdocs.drift.com/docs/drift-events) (beyond the 'ready' event) but the `drift` script has to be loaded and ready before you can attach any listeners. 

Right now, to attach listeners to drift events you can wrap either the `Drift` component and orchestrate it yourself based on the `state` returned from the `useChat` hook being set to `complete`. A simple example:

```ts
  const [ state ] = useChat();

  useEffect(() => {
    if (state === "complete") {
       window.drift.on('conversationStarted', () => {})
    }
  }, [ state ]);
```

## Describe the solution you’d like to see
This can be introduced, likely without a breaking change, by accepting an optional `events` prop in the  [`Drift` component](https://github.com/calibreapp/react-live-chat-loader/blob/main/src/components/Drift/index.tsx) and registering the provided event handlers with drift once appropriate. 

The `events` prop type could be an object of Drift event names to handlers:
```ts
const driftListeners: DriftEventHandlers = {
  startConversation: ({ conversationId }) => {
    // do something here...
  },
};
```

This type could defined using something like:

__I'm new to TypeScript so take this with a grain of salt__
```ts
type DriftEventPayloads = {
  startConversation: {
    conversationId: number;
    inboxId: number;
  };
  chatOpen: undefined;
  chatClose: undefined;
  // ... all other supported events
};

type DriftEventHandler<P> = (data: P) => void;

export type DriftEventHandlers = {
  [K in keyof DriftEventPayloads]?: DriftEventHandler<DriftEventPayloads[K]>;
};
```

If this or an alternate solution makes sense I'm happy to submit a PR.

## Describe alternatives you’ve considered
It's possible to accept a prop in the `LiveChatLoaderProvider`, which in theory makes sense because that's where the initialization props are provided and extra props are included in the context. However, it's unclear to me if event listening would be applicable/beneficial with other providers and would require a change to `useChat` and the provider api.

**Comment by mikedijkstra** [comment]
Hi @myleslinder — Thanks for submitting your feature request, I can see how it could be handy to be able to more easily add provider related events and configuration once the script has loaded.

What do you think about an alternative solution where you can execute a callback once the script has been loaded? This could be a way to allow all providers to do a similar thing without having to implement provider specific code.

We could have two callbacks: `onLoaded` which is executed once the provider script has been loaded and `onReady` which is executed once the provider is ready.

The callbacks could be passed through the `LiveChatLoaderProvider` and then passed to the provider via [loadChat](https://github.com/calibreapp/react-live-chat-loader/blob/main/src/hooks/useChat.ts#L87) and then ultimately called within the provider when we have either [loaded the script](https://github.com/calibreapp/react-live-chat-loader/blob/main/src/providers/drift.ts#L80) or determined the [provider is ready](https://github.com/calibreapp/react-live-chat-loader/blob/main/src/providers/drift.ts#L84).

With this in place I imagine you could set what you need to set on `window.drift` once the script has loaded, e.g.:

```jsx
const setupEvents = () => {
  window.drift.on('conversationStarted', () => {})
}

<LiveChatLoaderProvider … onLoaded={setupEvents}  … />

```

Thoughts?

**Comment by myleslinder** [comment]
Hey @mikedijkstra, thanks for the prompt response. That approach with the `onReady` callback will work for setting event handlers and it makes sense to not add additional provider specific code.

With regards to the `onLoaded` callback, ideally it could be fired before [the actual initialization of the widget](https://github.com/calibreapp/react-live-chat-loader/blob/main/src/providers/drift.ts#L81). This is mostly to allow for user identification. If you're identifying users with Drift you're supposed to call `identify` prior to calling `load`. The same thing exists with Intercom (with `boot` instead of `load`), although I think you can just set `intercomSettings` on the window anytime prior to loading the script.

**Comment by mikedijkstra** [comment]
@myleslinder Okay. Maybe we call the `onLoad` one `beforeLoad` then and fire it [right before the line you linked to](https://github.com/calibreapp/react-live-chat-loader/blob/main/src/providers/drift.ts#L81) (just inside the if check). What do you think?

Would you be happy to put together a PR for these two callbacks?
